# Header
menu:
  home:
    url: /
  archives:
    url: /archives
  tags:
    url: /tags
  github:
    url: https://github.com/2hf
    target: _blank
  #weibo:
   # url: http://www.weibo.com/
    #target: _blank

rss: /atom.xml

#你的头像url
avatar: /img/avatar.png

# email
email: zh.f@outlook.com

# Content
tags:
  title: "#TAG"

excerpt_link: more
mathjax: false
archive_yearly: true

#是否开启分享
share: true

#是否开启toc
#toc: false
toc:
  list_number: false  # 是否显示数字排序

#站长统计，如要开启，输入CNZZ站点id
#cnzz: false
cnzz: 1257688433

# Miscellaneous
google_analytics: ''
favicon: /favicon.ico

# less
less:
  paths:
    - source/css/style.less


#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: elbarco
